### ISSUE TITLE
Simplifying the Service Block object

### ISSUE THREAD

**Issue by ajstarks** [juju/jujusvg#10]
Would a simple roundrect work better than the complicated path for the serviceBlock object?

**Comment by makyo** [comment]
This is sort of addressed by #23 which moves the asset of the service block to its own file which can thus be included.  It doesn't really alleviate pathitis, but it does keep design happy, and helps us out so that we're not rewriting their assets in SVGo-ese.  We can simply drop design's assets in there, then `canvas.Use` them down the road.

**Comment by makyo** [comment]
Obviated by #41
